### ISSUE TITLE
🐛 [BUG] - [FIX] the main login redirect to the homepage

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#264] opened 2023-08-24 20:50 UTC
### Description

Hi
in authentication.tpl it is necessary to edit the 

<a href="{$urls.pages.register}">

to this

<a href="{$urls.pages.register}" data-link-action="display-register-form">

without data-link-action="display-register-form" the redirect will go to the homepage

![1](https://github.com/Oksydan/falcon/assets/653230/3730a05c-df2b-49d6-aab1-6623c245abe1)

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

theme

### Reproduction steps

```bash
1. it is necessary to edit authentication.tpl
```

**Comment by Oksydan** [comment] 2023-08-24 21:02
HI @maofree,

I am sorry but I don't understand you issue. 
I have no idea how to reproduce it and what is your issue at all 🤔

**Comment by maofree** [comment] 2023-08-24 21:07
if you compare the falcon authentication.tpl with the classic one you will see the missing of 
data-link-action="display-register-form"

if I go to the "Login and registration" and I set email and password, after that I go to the homepage and not into the account page

![1](https://github.com/Oksydan/falcon/assets/653230/3235c147-ca28-41c0-8d54-1bcd31db263e)

**Comment by Oksydan** [comment] 2023-08-24 21:13
Sorry @maofree I am not able to reproduce it. I am being redirected to account page instead of home. 
BTW data attributes are only readable in front end part of application. I don't think missing data-link-action attribute might cause this kind of issue 🤔

**Comment by maofree** [comment] 2023-08-24 21:47
probably it is due from some changes that I've done
I've removed customer-links.tpl and set again the classic customer account, to avoid problems with the other bug report. I prefer the normal solution, I think it is simpler and more understandable for a normal mobile user

**Comment by Oksydan** [comment] 2023-08-24 21:57
Ok, so I can close the issue. 
Feel free to open new one.

**Closed by Oksydan** 2023-08-24 21:57 UTC
Labels: bug, waiting for author
