### ISSUE TITLE
🐛 [BUG] - is_searchbar javascript error - TypeError: Cannot read properties of undefined (reading 'update')

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#351] opened 2023-11-28 11:27 UTC
### Description

Hi
today I've seen this error in the console log when a write something in the input field of search bar
the problem is into theme.js

![1](https://github.com/Oksydan/falcon/assets/653230/ab287c7f-2883-46b8-ba0b-26690db772b1)

![22](https://github.com/Oksydan/falcon/assets/653230/2dd24682-8309-4e3d-bd64-ce4e6e57b61b)

perhaps you have already solved it in version 4 of the module, however I will report the error to you

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

is_searchbar

### Reproduction steps

```bash
1. digit something in the search bar
2. look in the console log
```

**Comment by Oksydan** [comment] 2023-11-29 23:40
Hi @maofree,

thank you for creating an issue.
I was able to reproduce the problem.
I am adding this to `is_searchbar` epic for the new version.

**Comment by Oksydan** [comment] 2023-12-11 01:00
Hi @maofree,

problem has been fixed. I am closing this issue. 
It will be available in new 4.0.0 version of is_searchbar module.
Thank you for your contribution.

**Closed by Oksydan** 2023-12-11 01:00 UTC
Labels: bug, is_searchbar

**Comment by maofree** [comment] 2023-12-12 08:23
Hi @Oksydan 
Could you correct the portion of code to remove this error? so I remove it in the current version too. I have seen the changes made in the module but they also relate to many other aspects

**Comment by Oksydan** [comment] 2023-12-12 17:38
Hi @maofree 

Tbh I wasn't able to reproduce it again. Since I rewrote whole js od the module it's not a valid issue anymore. Did you remove one of the Falcon theme core components? For example lazyload in your project?

**Comment by maofree** [comment] 2023-12-12 17:39
Hi
yes I've removed lazyload

**Comment by Oksydan** [comment] 2023-12-12 22:04
Your problem comes from this line https://github.com/Oksydan/is_searchbar/blob/main/_theme_dev/src/js/theme/index.js#L24

**Comment by maofree** [comment] 2023-12-12 22:46
Hi @Oksydan 
yes you are right, removing that line the problem is solved

thanks alot
