### ISSUE TITLE
🐛 [BUG] - is_themecore error after prestashop 8.0.1 upgrade

### ISSUE THREAD

**Issue by StefanVonRanda** [Oksydan/falcon#163] opened 2023-01-09 09:17 UTC
### Description

I've upgraded a Prestashop 8.0.0 to 8.0.1 installation without issue.
However, when trying to access the backoffice of the newly upgraded install, I get the following Symphony Exception in debug mode.

Stacktrace:
```
Symfony\Component\Routing\Exception\RouteNotFoundException:
Unable to generate a URL for the named route "is_themecore_module_settings" as such route does not exist.

  at vendor/symfony/symfony/src/Symfony/Component/Routing/Generator/CompiledUrlGenerator.php:50
  at Symfony\Component\Routing\Generator\CompiledUrlGenerator->generate('is_themecore_module_settings', array(), 1)
     (vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php:252)
  at Symfony\Component\Routing\Router->generate('is_themecore_module_settings', array(), 1)
     (src/PrestaShopBundle/Service/Routing/Router.php:67)
  at PrestaShopBundle\Service\Routing\Router->generate('is_themecore_module_settings')
     (classes/Link.php:872)
  at LinkCore->getTabLink(array('id_tab' => '129', 'id_parent' => '70', 'position' => '3', 'module' => 'is_themecore', 'class_name' => 'themecoreSettings', 'route_name' => 'is_themecore_module_settings', 'active' => '0', 'enabled' => '1', 'icon' => '', 'wording' => 'Theme core module settings', 'wording_domain' => 'Modules.isthemecore.Admin', 'name' => 'Theme core module settings'))
     (classes/controller/AdminController.php:2143)
  at AdminControllerCore->getTabs('70', 1)
     (classes/controller/AdminController.php:2144)
  at AdminControllerCore->getTabs()
     (classes/controller/AdminController.php:2020)
  at AdminControllerCore->initHeader()
     (classes/controller/Controller.php:315)
  at ControllerCore->run()
     (classes/Dispatcher.php:510)
  at DispatcherCore->dispatch()
     (kontrolpanel/index.php:92)
```

### Node.js version

v16.15

### php version

v8.08

### OS and it's version

MacOS Monterey ARM

### Browsers

Chrome

### Required module/theme

is_themecore

### Reproduction steps

```bash
1. Install Falcon theme with associated modules on a Prestashop 8.0.0 instance
2. Upgrade Prestashop 8.0.0 instance to 8.0.1 using "1-Click Upgrade" module
3. Go to backoffice of newly upgraded 8.0.1 instance
4. See error
```

### Logs

```bash
Symfony\Component\Routing\Exception\RouteNotFoundException:
Unable to generate a URL for the named route "is_themecore_module_settings" as such route does not exist.

  at vendor/symfony/symfony/src/Symfony/Component/Routing/Generator/CompiledUrlGenerator.php:50
  at Symfony\Component\Routing\Generator\CompiledUrlGenerator->generate('is_themecore_module_settings', array(), 1)
     (vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php:252)
  at Symfony\Component\Routing\Router->generate('is_themecore_module_settings', array(), 1)
     (src/PrestaShopBundle/Service/Routing/Router.php:67)
  at PrestaShopBundle\Service\Routing\Router->generate('is_themecore_module_settings')
     (classes/Link.php:872)
  at LinkCore->getTabLink(array('id_tab' => '129', 'id_parent' => '70', 'position' => '3', 'module' => 'is_themecore', 'class_name' => 'themecoreSettings', 'route_name' => 'is_themecore_module_settings', 'active' => '0', 'enabled' => '1', 'icon' => '', 'wording' => 'Theme core module settings', 'wording_domain' => 'Modules.isthemecore.Admin', 'name' => 'Theme core module settings'))
     (classes/controller/AdminController.php:2143)
  at AdminControllerCore->getTabs('70', 1)
     (classes/controller/AdminController.php:2144)
  at AdminControllerCore->getTabs()
     (classes/controller/AdminController.php:2020)
  at AdminControllerCore->initHeader()
     (classes/controller/Controller.php:315)
  at ControllerCore->run()
     (classes/Dispatcher.php:510)
  at DispatcherCore->dispatch()
     (kontrolpanel/index.php:92)
```

**Comment by Oksydan** [comment] 2023-01-09 21:22
Hi @StefanVonRanda,

can you check your database table `prefix_tab` and look for column `route_name` with value `is_themecore_module_settings`.
Can you show me result of that row?
Also please check if that route isn't duplicated in DB for some reasons. 

Ofc you could just reset module and it should remove all tabs from DB and insert new one but that's not perfect solution.

**Comment by StefanVonRanda** [comment] 2023-01-10 10:01
Found no duplicates.
I did find the entry in ps_tab, the values are:
```
id: 129
parent_id: 70
position: 3
module: is_themecore
class_name: themecoreSettings
value: is_themecore_module_settings
active: 0
enabled: 1
wording: Theme core module settings
wording_domain: Modules.isthemecore.Admin
```

**Comment by Oksydan** [comment] 2023-01-15 22:20
Hi @StefanVonRanda,

unfortunately I was not able to reproduce an issue 😕.
Can you just reset that module and tell me if problem still persist? 
I know that's not best solution but module don't create any table in DB so no data will be lost. 
I have no idea what could happened during upgrade process 😕

**Comment by pbousek** [comment] 2023-02-12 20:16
Hello, I got similar issue

[2023-02-12 20:56:33] php.CRITICAL: Uncaught Exception: Unable to generate a URL for the named route "is_themecore_module_settings" as such route does not exist. {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"is_themecore_module_settings\" as such route does not exist. at /var/www/b3da/htdocs/planko/eshop/var/cache/dev/appDevDebugProjectContainerUrlGenerator.php:615)"} []
[2023-02-12 20:56:33] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Routing\Exception\RouteNotFoundException: "Unable to generate a URL for the named route "is_themecore_module_settings" as such route does not exist." at /var/www/b3da/htdocs/planko/eshop/var/cache/dev/appDevDebugProjectContainerUrlGenerator.php line 615 {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"is_themecore_module_settings\" as such route does not exist. at /var/www/b3da/htdocs/planko/eshop/var/cache/dev/appDevDebugProjectContainerUrlGenerator.php:615)"} []

Presta version 1.7.8.8 
I perform cache clearing ... but result is still the same.

Petr

**Comment by Oksydan** [comment] 2023-02-13 11:50
Hi @pbousek,

I am not sure but you case seems to be different. 
Please create new issue and fill required fields with informations. 
Also provide me is_themecore version.

**Comment by Oksydan** [comment] 2023-03-05 22:30
Hi @StefanVonRanda,

since I had no news from you in 30 days.
I am going to close this issue. Feel free to open new issue or create a new one if you are still facing an issue.

**Closed by Oksydan** 2023-03-05 22:30 UTC
Labels: bug, waiting for author
