### ISSUE TITLE
🐛 [BUG] - Change product variant hide product details

### ISSUE THREAD

**Issue by ytilotti** [Oksydan/falcon#167] opened 2023-01-12 09:32 UTC
### Description

Change the product variant hide the content of product details.

![image](https://user-images.githubusercontent.com/5848945/212030250-e03c159c-5fc3-439a-9990-ec8725e0f775.png)
![image](https://user-images.githubusercontent.com/5848945/212030153-4af8acd4-7d25-4207-9f57-7b699fb57b00.png)

### Node.js version

v14.21.1

### php version

v7.4

### OS and it's version

Docker WLS 2 Ubuntu

### Browsers

Chrome

### Required module/theme

theme v3

### Reproduction steps

```bash
1. Go to a product with variant in front
2. Click on a variant
3. Scroll down to product details
4. The block is empty
```

**Comment by Oksydan** [comment] 2023-01-15 22:16
HI @ytilotti,

thank you for creating an issue.
I was able to reproduce an issue and it's looking like a regression. 
I will fix it ASAP.

**Comment by Oksydan** [comment] 2023-01-23 23:26
Hi @ytilotti,

new version 3.0.2 has been released. 
I am closing this issue since it has been resolved in new version.

Thank you for creating an issue.

**Closed by Oksydan** 2023-01-23 23:26 UTC
Labels: bug, 3.0.2, major
