### ISSUE TITLE
🐛 [BUG] - Custom control label form not unescape HTML

### ISSUE THREAD

**Issue by ytilotti** [Oksydan/falcon#172] opened 2023-01-16 19:57 UTC
### Description

The HTML in label of custom control is not unescape:
![image](https://user-images.githubusercontent.com/5848945/212756835-6fcec1e9-54e6-456c-b102-4de7cae4ab62.png)

### Node.js version

v14.21

### php version

v7.4

### OS and it's version

Docker

### Browsers

Chrome

### Required module/theme

theme v3

### Reproduction steps

```bash
1. Go to front office
2. Add a product in the cart
3. Go to the cart
4. Make an order
5. On the first step we can see the problems
```

**Comment by Oksydan** [comment] 2023-01-19 19:25
Hi @ytilotti,

thank you for creating an issue and PR. 
I was able to reproduce an issue. 
It is related to upgraded smarty in PS 8.0. 

Thank you for your contribution.

**Comment by Oksydan** [comment] 2023-01-23 23:26
Hi @ytilotti,

new version 3.0.2 has been released. 
I am closing this issue since it has been resolved in new version.

Thank you for creating an issue and PR.

**Closed by Oksydan** 2023-01-23 23:26 UTC
Labels: bug, minor, 3.0.2
