### ISSUE TITLE
🐛 [BUG] - Unable to generate a URL for the named route "is_themecore_module_settings" as such route does not exist.

### ISSUE THREAD

**Issue by pbousek** [Oksydan/falcon#186] opened 2023-02-13 20:01 UTC
### Description

we got this error after falcon theme installation:

CRITICAL20:46:55 | php | Uncaught Exception: Unable to generate a URL for the named route "is_themecore_module_settings" as such route does not exist.
-- | -- | --
CRITICAL20:46:55 | request | Uncaught PHP Exception Symfony\Component\Routing\Exception\RouteNotFoundException: "Unable to generate a URL for the named route "is_themecore_module_settings" as such route does not exist." at /var/www/b3da/htdocs/planko/eshop/var/cache/dev/appDevDebugProjectContainerUrlGenerator.php line 615

after login to presta admin page we got this:
![image](https://user-images.githubusercontent.com/21953786/218562391-25d935f8-e36f-47a9-a3dc-7f39a5ed66bc.png)

### Node.js version

v16.19.0

### php version

v7.4

### OS and it's version

Linux 

### Browsers

Chrome

### Required module/theme

is_themecore v3.0.1

### Reproduction steps

```bash
1. Go to 'Presta site admin and fill the login info'
2. Click on 'login'
3. See error
```

### Logs

```bash
[2023-02-08 13:15:26] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "is_themecore_module_settings" as such route does not exist.")." at /var/www/b3da/htdocs/planko/eshop/src/PrestaShopBundle/Resources/views/Admin/layout.html.twig line 37 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"is_themecore_module_settings\" as such route does not exist.\"). at /var/www/b3da/htdocs/planko/eshop/src/PrestaShopBundle/Resources/views/Admin/layout.html.twig:37, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"is_themecore_module_settings\" as such route does not exist. at /var/www/b3da/htdocs/planko/eshop/var/cache/prod/appProdProjectContainerUrlGenerator.php:599)"} []
```

**Comment by Oksydan** [comment] 2023-02-13 21:36
Hi @pbousek,

Looks like you are using wrong version of module for your prestashop version.
For version below 8.0 you should use `is_themecore` in version 2.X instead of 3.X.

**Comment by pbousek** [comment] 2023-02-13 21:40
So it means that I need to use falcon 2.x and is_themecore 2.x? I get little bit lost in those compatibility tables.

Thanks

Petr

**Comment by Oksydan** [comment] 2023-02-13 22:41
Yes, if you are building your store with prestashop below version 8.0, you have to use falcon theme 2.X and is_themecore version 2.X.
Compatibility tabels might be a bit confusing but I have no idea how to make it easier to understand 😕 
Between major version we are doing BC and sometimes dropping php/prestashop support. It's all in change logs for every release if we are dropping support for something.

**Comment by pbousek** [comment] 2023-02-13 22:44
ok, so thats my fault, I will try it with 2.x ... I think that this issue could be closed.

Thanks 

Petr

**Comment by globalworming** [comment] 2023-02-21 10:02
I am getting the same error using 

falcon 3.0.2
is_themecore 3.0.1
is_imageslider 2.0.1
is_searchbar 2.0.0
is_shoppingcart 2.0.0

when clicking "use this theme" in the admin design config


<details>
  <summary>Stack Trace</summary>
  
  ```
  Twig\Error\RuntimeError:
An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "is_themecore_module_settings" as such route does not exist.").

  at src/PrestaShopBundle/Resources/views/Admin/layout.html.twig:38
  at Twig\Template->displayWithErrorHandling(array('baseShopUrl' => 'http://172.23.0.3/', 'shopLogosForm' => object(FormView), 'headerLogoPath' => '/img/logo.png', 'mailLogoPath' => '/img/logo.png', 'invoiceLogoPath' => '/img/logo.png', 'faviconPath' => '/img/favicon.ico', 'currentlyUsedTheme' => object(Theme), 'notUsedThemes' => array('classic' => object(Theme)), 'isDevModeOn' => true, 'isSingleShopContext' => true, 'isMultiShopFeatureUsed' => false, 'adaptThemeToRtlLanguagesForm' => object(FormView), 'isInstalledRtlLanguage' => false, 'shopName' => 'PrestaShop', 'enableSidebar' => true, 'help_link' => '/admin074glnyfjklwzhcgnrk/index.php/common/sidebar/https%253A%252F%252Fhelp.prestashop-project.org%252Fen%252Fdoc%252FAdminThemes%253Fversion%253D8.0.1%2526country%253Den/Help?_token=XoxoPVpVF6Rgvqd9HPyPggwGxer-MCx37wrjYi02mm8', 'theme' => object(Theme), 'default_currency' => object(Currency), 'default_currency_symbol' => '€', 'root_url' => '/', 'js_translatable' => array(), 'rtl_suffix' => '', 'app' => object(AppVariable), 'webpack_server' => false, 'multistore_field_prefix' => 'multistore_', 'modify_all_shops_prefix' => 'modify_all_shops_', 'disabling_switch_prefix' => 'disabling_switch_', 'layoutTitle' => 'Theme & Logo > Theme', 'layoutHeaderToolbarBtn' => array('add' => array('href' => '/admin074glnyfjklwzhcgnrk/index.php/improve/design/themes/import?_token=XoxoPVpVF6Rgvqd9HPyPggwGxer-MCx37wrjYi02mm8', 'desc' => 'Add new theme', 'icon' => 'add'), 'export' => array('href' => '/admin074glnyfjklwzhcgnrk/index.php/improve/design/themes/export?_token=XoxoPVpVF6Rgvqd9HPyPggwGxer-MCx37wrjYi02mm8', 'desc' => 'Export current theme', 'icon' => 'cloud_download'))), array('javascripts' => array(object(__TwigTemplate_5e30edc4d92d335c6daf741eb9a894bf), 'block_javascripts'), 'translate_javascripts' => array(object(__TwigTemplate_c21fec1586fe3ef5ed1b56a186b034e8), 'block_translate_javascripts'), 'content_header' => array(object(__TwigTemplate_c21fec1586fe3ef5ed1b56a186b034e8), 'block_content_header'), 'session_alert' => array(object(__TwigTemplate_c21fec1586fe3ef5ed1b56a186b034e8), 'block_session_alert'), 'sidebar_right' => array(object(__TwigTemplate_c21fec1586fe3ef5ed1b56a186b034e8), 'block_sidebar_right'), 'content' => array(object(__TwigTemplate_5e30edc4d92d335c6daf741eb9a894bf), 'block_content')))
     (vendor/twig/twig/src/Template.php:367)
  at Twig\Template->display(array('baseShopUrl' => 'http://172.23.0.3/', 'shopLogosForm' => object(FormView), 'headerLogoPath' => '/img/logo.png', 'mailLogoPath' => '/img/logo.png', 'invoiceLogoPath' => '/img/logo.png', 'faviconPath' => '/img/favicon.ico', 'currentlyUsedTheme' => object(Theme), 'notUsedThemes' => array('classic' => object(Theme)), 'isDevModeOn' => true, 'isSingleShopContext' => true, 'isMultiShopFeatureUsed' => false, 'adaptThemeToRtlLanguagesForm' => object(FormView), 'isInstalledRtlLanguage' => false, 'shopName' => 'PrestaShop', 'enableSidebar' => true, 'help_link' => '/admin074glnyfjklwzhcgnrk/index.php/common/sidebar/https%253A%252F%252Fhelp.prestashop-project.org%252Fen%252Fdoc%252FAdminThemes%253Fversion%253D8.0.1%2526country%253Den/Help?_token=XoxoPVpVF6Rgvqd9HPyPggwGxer-MCx37wrjYi02mm8', 'theme' => object(Theme), 'default_currency' => object(Currency), 'default_currency_symbol' => '€', 'root_url' => '/', 'js_translatable' => array(), 'rtl_suffix' => '', 'app' => object(AppVariable), 'webpack_server' => false, 'multistore_field_prefix' => 'multistore_', 'modify_all_shops_prefix' => 'modify_all_shops_', 'disabling_switch_prefix' => 'disabling_switch_', 'layoutTitle' => 'Theme & Logo > Theme', 'layoutHeaderToolbarBtn' => array('add' => array('href' => '/admin074glnyfjklwzhcgnrk/index.php/improve/design/themes/import?_token=XoxoPVpVF6Rgvqd9HPyPggwGxer-MCx37wrjYi02mm8', 'desc' => 'Add new theme', 'icon' => 'add'), 'export' => array('href' => '/admin074glnyfjklwzhcgnrk/index.php/improve/design/themes/export?_token=XoxoPVpVF6Rgvqd9HPyPggwGxer-MCx37wrjYi02mm8', 'desc' => 'Export current theme', 'icon' => 'cloud_download'))), array('content' => array(object(__TwigTemplate_5e30edc4d92d335c6daf741eb9a894bf), 'block_content'), 'javascripts' => array(object(__TwigTemplate_5e30edc4d92d335c6daf741eb9a894bf), 'block_javascripts')))
     (var/cache/dev/twig/4c/4cce20d2bfea4a335eff3466def6d082.php:54)
  at __TwigTemplate_5e30edc4d92d335c6daf741eb9a894bf->doDisplay(array('baseShopUrl' => 'http://172.23.0.3/', 'shopLogosForm' => object(FormView), 'headerLogoPath' => '/img/logo.png', 'mailLogoPath' => '/img/logo.png', 'invoiceLogoPath' => '/img/logo.png', 'faviconPath' => '/img/favicon.ico', 'currentlyUsedTheme' => object(Theme), 'notUsedThemes' => array('classic' => object(Theme)), 'isDevModeOn' => true, 'isSingleShopContext' => true, 'isMultiShopFeatureUsed' => false, 'adaptThemeToRtlLanguagesForm' => object(FormView), 'isInstalledRtlLanguage' => false, 'shopName' => 'PrestaShop', 'enableSidebar' => true, 'help_link' => '/admin074glnyfjklwzhcgnrk/index.php/common/sidebar/https%253A%252F%252Fhelp.prestashop-project.org%252Fen%252Fdoc%252FAdminThemes%253Fversion%253D8.0.1%2526country%253Den/Help?_token=XoxoPVpVF6Rgvqd9HPyPggwGxer-MCx37wrjYi02mm8', 'theme' => object(Theme), 'default_currency' => object(Currency), 'default_currency_symbol' => '€', 'root_url' => '/', 'js_translatable' => array(), 'rtl_suffix' => '', 'app' => object(AppVariable), 'webpack_server' => false, 'multistore_field_prefix' => 'multistore_', 'modify_all_shops_prefix' => 'modify_all_shops_', 'disabling_switch_prefix' => 'disabling_switch_', 'layoutTitle' => 'Theme & Logo > Theme', 'layoutHeaderToolbarBtn' => array('add' => array('href' => '/admin074glnyfjklwzhcgnrk/index.php/improve/design/themes/import?_token=XoxoPVpVF6Rgvqd9HPyPggwGxer-MCx37wrjYi02mm8', 'desc' => 'Add new theme', 'icon' => 'add'), 'export' => array('href' => '/admin074glnyfjklwzhcgnrk/index.php/improve/design/themes/export?_token=XoxoPVpVF6Rgvqd9HPyPggwGxer-MCx37wrjYi02mm8', 'desc' => 'Export current theme', 'icon' => 'cloud_download'))), array('content' => array(object(__TwigTemplate_5e30edc4d92d335c6daf741eb9a894bf), 'block_content'), 'javascripts' => array(object(__TwigTemplate_5e30edc4d92d335c6daf741eb9a894bf), 'block_javascripts')))
     (vendor/twig/twig/src/Template.php:394)
  at Twig\Template->displayWithErrorHandling(array('baseShopUrl' => 'http://172.23.0.3/', 'shopLogosForm' => object(FormView), 'headerLogoPath' => '/img/logo.png', 'mailLogoPath' => '/img/logo.png', 'invoiceLogoPath' => '/img/logo.png', 'faviconPath' => '/img/favicon.ico', 'currentlyUsedTheme' => object(Theme), 'notUsedThemes' => array('classic' => object(Theme)), 'isDevModeOn' => true, 'isSingleShopContext' => true, 'isMultiShopFeatureUsed' => false, 'adaptThemeToRtlLanguagesForm' => object(FormView), 'isInstalledRtlLanguage' => false, 'shopName' => 'PrestaShop', 'enableSidebar' => true, 'help_link' => '/admin074glnyfjklwzhcgnrk/index.php/common/sidebar/https%253A%252F%252Fhelp.prestashop-project.org%252Fen%252Fdoc%252FAdminThemes%253Fversion%253D8.0.1%2526country%253Den/Help?_token=XoxoPVpVF6Rgvqd9HPyPggwGxer-MCx37wrjYi02mm8', 'theme' => object(Theme), 'default_currency' => object(Currency), 'default_currency_symbol' => '€', 'root_url' => '/', 'js_translatable' => array(), 'rtl_suffix' => '', 'app' => object(AppVariable), 'webpack_server' => false, 'multistore_field_prefix' => 'multistore_', 'modify_all_shops_prefix' => 'modify_all_shops_', 'disabling_switch_prefix' => 'disabling_switch_'), array('content' => array(object(__TwigTemplate_5e30edc4d92d335c6daf741eb9a894bf), 'block_content'), 'javascripts' => array(object(__TwigTemplate_5e30edc4d92d335c6daf741eb9a894bf), 'block_javascripts')))
     (vendor/twig/twig/src/Template.php:367)
  at Twig\Template->display(array('baseShopUrl' => 'http://172.23.0.3/', 'shopLogosForm' => object(FormView), 'headerLogoPath' => '/img/logo.png', 'mailLogoPath' => '/img/logo.png', 'invoiceLogoPath' => '/img/logo.png', 'faviconPath' => '/img/favicon.ico', 'currentlyUsedTheme' => object(Theme), 'notUsedThemes' => array('classic' => object(Theme)), 'isDevModeOn' => true, 'isSingleShopContext' => true, 'isMultiShopFeatureUsed' => false, 'adaptThemeToRtlLanguagesForm' => object(FormView), 'isInstalledRtlLanguage' => false, 'shopName' => 'PrestaShop', 'enableSidebar' => true, 'help_link' => '/admin074glnyfjklwzhcgnrk/index.php/common/sidebar/https%253A%252F%252Fhelp.prestashop-project.org%252Fen%252Fdoc%252FAdminThemes%253Fversion%253D8.0.1%2526country%253Den/Help?_token=XoxoPVpVF6Rgvqd9HPyPggwGxer-MCx37wrjYi02mm8'))
     (vendor/twig/twig/src/Template.php:379)
  at Twig\Template->render(array('baseShopUrl' => 'http://172.23.0.3/', 'shopLogosForm' => object(FormView), 'headerLogoPath' => '/img/logo.png', 'mailLogoPath' => '/img/logo.png', 'invoiceLogoPath' => '/img/logo.png', 'faviconPath' => '/img/favicon.ico', 'currentlyUsedTheme' => object(Theme), 'notUsedThemes' => array('classic' => object(Theme)), 'isDevModeOn' => true, 'isSingleShopContext' => true, 'isMultiShopFeatureUsed' => false, 'adaptThemeToRtlLanguagesForm' => object(FormView), 'isInstalledRtlLanguage' => false, 'shopName' => 'PrestaShop', 'enableSidebar' => true, 'help_link' => '/admin074glnyfjklwzhcgnrk/index.php/common/sidebar/https%253A%252F%252Fhelp.prestashop-project.org%252Fen%252Fdoc%252FAdminThemes%253Fversion%253D8.0.1%2526country%253Den/Help?_token=XoxoPVpVF6Rgvqd9HPyPggwGxer-MCx37wrjYi02mm8'), array())
     (vendor/twig/twig/src/TemplateWrapper.php:40)
  at Twig\TemplateWrapper->render(array('baseShopUrl' => 'http://172.23.0.3/', 'shopLogosForm' => object(FormView), 'headerLogoPath' => '/img/logo.png', 'mailLogoPath' => '/img/logo.png', 'invoiceLogoPath' => '/img/logo.png', 'faviconPath' => '/img/favicon.ico', 'currentlyUsedTheme' => object(Theme), 'notUsedThemes' => array('classic' => object(Theme)), 'isDevModeOn' => true, 'isSingleShopContext' => true, 'isMultiShopFeatureUsed' => false, 'adaptThemeToRtlLanguagesForm' => object(FormView), 'isInstalledRtlLanguage' => false, 'shopName' => 'PrestaShop', 'enableSidebar' => true, 'help_link' => '/admin074glnyfjklwzhcgnrk/index.php/common/sidebar/https%253A%252F%252Fhelp.prestashop-project.org%252Fen%252Fdoc%252FAdminThemes%253Fversion%253D8.0.1%2526country%253Den/Help?_token=XoxoPVpVF6Rgvqd9HPyPggwGxer-MCx37wrjYi02mm8'))
     (vendor/twig/twig/src/Environment.php:277)
  at Twig\Environment->render('@PrestaShop/Admin/Improve/Design/Theme/index.html.twig', array('baseShopUrl' => 'http://172.23.0.3/', 'shopLogosForm' => object(FormView), 'headerLogoPath' => '/img/logo.png', 'mailLogoPath' => '/img/logo.png', 'invoiceLogoPath' => '/img/logo.png', 'faviconPath' => '/img/favicon.ico', 'currentlyUsedTheme' => object(Theme), 'notUsedThemes' => array('classic' => object(Theme)), 'isDevModeOn' => true, 'isSingleShopContext' => true, 'isMultiShopFeatureUsed' => false, 'adaptThemeToRtlLanguagesForm' => object(FormView), 'isInstalledRtlLanguage' => false, 'shopName' => 'PrestaShop', 'enableSidebar' => true, 'help_link' => '/admin074glnyfjklwzhcgnrk/index.php/common/sidebar/https%253A%252F%252Fhelp.prestashop-project.org%252Fen%252Fdoc%252FAdminThemes%253Fversion%253D8.0.1%2526country%253Den/Help?_token=XoxoPVpVF6Rgvqd9HPyPggwGxer-MCx37wrjYi02mm8'))
     (vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerTrait.php:235)
  at Symfony\Bundle\FrameworkBundle\Controller\AbstractController->render('@PrestaShop/Admin/Improve/Design/Theme/index.html.twig', array('baseShopUrl' => 'http://172.23.0.3/', 'shopLogosForm' => object(FormView), 'headerLogoPath' => '/img/logo.png', 'mailLogoPath' => '/img/logo.png', 'invoiceLogoPath' => '/img/logo.png', 'faviconPath' => '/img/favicon.ico', 'currentlyUsedTheme' => object(Theme), 'notUsedThemes' => array('classic' => object(Theme)), 'isDevModeOn' => true, 'isSingleShopContext' => true, 'isMultiShopFeatureUsed' => false, 'adaptThemeToRtlLanguagesForm' => object(FormView), 'isInstalledRtlLanguage' => false, 'shopName' => 'PrestaShop', 'enableSidebar' => true, 'help_link' => '/admin074glnyfjklwzhcgnrk/index.php/common/sidebar/https%253A%252F%252Fhelp.prestashop-project.org%252Fen%252Fdoc%252FAdminThemes%253Fversion%253D8.0.1%2526country%253Den/Help?_token=XoxoPVpVF6Rgvqd9HPyPggwGxer-MCx37wrjYi02mm8'))
     (src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeController.php:107)
  at PrestaShopBundle\Controller\Admin\Improve\Design\ThemeController->indexAction(object(Request))
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:169)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:81)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, false)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request), 1, false)
     (admin074glnyfjklwzhcgnrk/index.php:81)                
  ```
</details>


![image](https://user-images.githubusercontent.com/2108984/220311668-958bf2ea-a51b-46a2-a0c0-cfcb5b0ab30a.png)


Checking the config page again, it seems the falcon theme is applied as "My current theme", still wondering if that exception will lead to problems elsewhere?

**Comment by Oksydan** [comment] 2023-03-05 22:37
Hi @globalworming,

I don't think that this exception might lead to any problems. 
Routes are only used to display controllers in your shop back ofifce.
If your is_themecore module configuration is working there is nothing to worry about.
I am still not sure what is causing this coz I wasn't able to reproduce it 😕 

I am going to close this issue. Please feel free to create new issue if you face any problem.
Thank you @pbousek for creating an issue. I hope that problem has been resolved.

**Closed by Oksydan** 2023-03-05 22:37 UTC
Labels: bug, waiting for author

**Comment by quddoss** [comment] 2023-03-12 10:41
It's related to the cache. This is a prestashop problem ... 

To ignore this error do this steps:
1. Login to dashboard > theme & logo.
2. Clear cache manually, delete all folders from var/cache/
3. Activate the new theme.
4. Done.

**Comment by quddoss** [comment] 2023-03-12 11:00
Or another options is to change in `Advanced Parameters > Performance > Smarty` 
Template compilation from `"Never recompile template files"` to `"Recompile templates if the files have been updated"`
