### ISSUE TITLE
🚀 [REQUEST] - Canonical Url is missing from the homepage

### ISSUE THREAD

**Issue by maofree** [Oksydan/falcon#376] opened 2024-01-18 22:38 UTC
### Description

Hi
I've seen that the homepage is without the canonical url. I think it is very useful to prevent duplication issues

using this code into head.tpl the problem is fixed

`  {if $page.canonical}
    <link rel="canonical" href="{$page.canonical}">
  {elseif $page.page_name eq 'index'}
    <link rel="canonical" href="{$urls.pages.index}">
  {/if}`

![1](https://github.com/Oksydan/falcon/assets/653230/16fa5c6c-6b07-427b-ab44-264611309d9f)

bye

### Node.js version

v16

### php version

8.1

### OS and it's version

linux

### Browsers

Chrome

### Required module/theme

theme

### Reproduction steps

```bash
1. Go to head.tpl
```

**Comment by Oksydan** [comment] 2024-01-22 22:28
Hi @maofree,

ok, we could modify it here but I am not sure thb that we should do it 🤔.
`$page.canonical` is assigned in frontController via `Controller::getCanonicalURL()` method. If canonical should be set to the same url maybe it should be proposal to PrestaShop core not theme. I am not SEO expert and my knowledge in this subject is a bit limited. Can you send me resource where can I read more about it. 
If it's working this way in PrestaShop core it's not a bug but feature request.

**Comment by maofree** [comment] 2024-01-22 22:33
Hi
I will open a ticket on prestashop's github.
canonical URLs are used to protect pages from duplication, both internal to the site and external if they made a copy of the site on other servers. at an SEO level, in this way Google would only index the reported page.
you can see it on Google Search Console, for example with sites that have multiple languages and currencies, you would see that Google reports errors because it sees duplications without a canonical URL. A bit like what happens with pagination

**Comment by maofree** [comment] 2024-01-22 22:41
done
https://github.com/PrestaShop/PrestaShop/issues/35133

**Comment by Oksydan** [comment] 2024-01-24 13:33
Hi @maofree,

thank you for creating this issue. 
I will close it for now because the PrestaShop project is fixing it on the core side.

**Closed by Oksydan** 2024-01-24 13:33 UTC
