### ISSUE TITLE
🐛 [BUG] - Footer link style ps_emailalerts

### ISSUE THREAD

**Issue by ytilotti** [Oksydan/falcon#165] opened 2023-01-11 16:39 UTC
### Description

The link of ps_emailalerts has no the same style of others links in the footer.

### Node.js version

v14.21.1

### php version

v7.4

### OS and it's version

Docker WLS 2 Ubuntu

### Browsers

Chrome

### Required module/theme

ps_emailalerts

### Reproduction steps

```bash
1. Active the module ps_emailalerts 
2. Go to the home and check the footer
```

**Comment by Oksydan** [comment] 2023-01-11 19:40
Hi @ytilotti,

thank you for creating an issue and for PR ❤️ 
I was able to reproduce an issue.

**Comment by Oksydan** [comment] 2023-01-23 23:27
Hi @ytilotti,

new version 3.0.2 has been released. 
I am closing this issue since it has been resolved in new version.

Thank you for creating an issue and PR.

**Closed by Oksydan** 2023-01-23 23:27 UTC
Labels: bug, minor, PR available, 3.0.2
